name: Generate Snake

on:
  schedule:
    # Runs at 12:00 AM UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Download the Snake Action
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Generate the Snake animation
      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/snake.svg

      # Commit and push the Snake animation to the `output` branch
      - name: Commit and push to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f dist/snake.svg
          git commit -m "Generate Snake animation"
          git push origin output
